version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123@Ntara$!!
      MYSQL_DATABASE: trackingsystem_db
    ports:
      - "3306:3306"
    networks:
      - backend

  app:
    build: .
    container_name: vehicle-tracking-app
    ports:
      - "9093:9093"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/trackingsystem_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123@Ntara$!!
    networks:
      - backend

networks:
  backend:
